import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import useSWR from 'swr';

export default function Home({ data }) {

  // const { data, error } = useSWR(`/api/people`,
  // (...args) => fetch(...args).then(res => res.json()))

  // console.log("data", data);

  if(!data) return <div>Loading....</div>

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {data.map(person => (
            <li key={person.id}>
              <Link href={`/person/${person.id}`}>
                <a>{person.name}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {

  // cannot use hooks inside here  
  const res = await fetch(`https://nextjs-demo-nov5-21.vercel.app/api/people`)
  const data = await res.json()
  // By returning { props: data }, the Onw component
  // will receive `data` as a prop at build time
  return {
    props: {
      data,
    },
  }
}
